### ISSUE TITLE
train results

### ISSUE THREAD

**Issue by lsrock1** [burnpiro/tiny-face-detection-tensorflow2#3]
Thanks for your wonderful work!
how much val_iou do you get on the default training config?
I only got 22%.

**Comment by burnpiro** [comment]
Hi, i don't really remember how much did i get on default config (it was couple months ago). I know that the best result was around  0.64 but it's not that important because even if most of IOUs are quite low they have high intersection value. If you look at that sample prediction, it has a quite low IOU but it's still a great prediction (basically a crop of the original area). It's good enough for the face because dataset specifies larger boxes that just a face (they consist of things like ears, hairs, etc).

It's not the best model for the job but I was just wondering if we could use mobilenet pretrained on imagenet and fit it to be good enough for detecting faces. If you're looking for models designed to detect faces check out BlazeFace or similar work.

**Comment by lsrock1** [comment]
Thank you!
